### ISSUE TITLE
Preferred citation/reference

### ISSUE THREAD

**Issue by nggsam** [DwangoMediaVillage/keras_compressor#6]
Hi,
We're working on a research paper and we've used your repo. Is this a preferred way to cite your work? Thank you!

**Comment by henry0312** [comment]
sorry for late response.
we don't have any papers, but we published an article, https://nico-opendata.jp/ja/casestudy/model_compression/index.html.
(sorry again for only Japanese)
For now, please refer this repository or the article.

**Comment by cocuh** [comment]
The suggested Japanese article does not contain algorithmic description, and we have no articles argued the algorithm used in this repository. Please cite this repository (like below). Thanks.
```
@misc{dmv-kerascompressor-2017,
  author = {DwangoMediaVillage},
  title = {keras\_compressor},
  year = {2017},
  publisher = {GitHub},
  journal = {GitHub repository},
  howpublished = {\url{https://github.com/DwangoMediaVillage/keras_compressor}},
}
```
